# 网络配置
server:
  # 服务器运行模式
  # - auto 自动代理
  # - http 仅http代理模式
  # - socks 仅socks代理模式
  mode: "auto"

  # 显示更详细日志，默认为false。设置为true将会打印更多日志记录。
  verbose: true

  # Http 代理服务配置
  http:
    # 禁用Http代理，默认为false，即启用Http代理
    # disabled: false

    # Http代理绑定地址，默认为本机所有网卡
    # bind: "0.0.0.0"

    # 监听端口，Http代理默认端口为 1080。有效端口为 (10 ~ 65535)
    port: 1080

  # Socks5 代理服务配置
  socks:
    # 禁用Socks代理，默认为false，即启用Socket代理
    # disabled: false

    # Socket代理绑定地址，默认为本机所有网卡
    # bind: "0.0.0.0"

    # 监听端口，Http代理默认端口为 1081。有效端口为 (10 ~ 65535)
    port: 1081

# 认证授权
authenticator:
  # 启用认证功能。默认为关闭认证，即允许任何客户端无认证连接。
  # 你需要将enabled设置为true来启用认证，同时需要设置认证方式。
  enabled: true

  # 认证用户列表
  basic:
    user1: "rocket-proxy"

# Resolver 配置
resolver:
  cache_size: 10000
  cache_ttl: 60
  hosts:
    #示例 domain: ip
    "fake.domain.com": "127.0.0.1"

# 连接访问策略组
ruleset:
  # 顺序：按以下顺序检查访问策略。
  - type: ipnet
    access: allow
    origin: source
    address:
      - "172.254.1.0/24"
      - "172.254.2.0/24"
  - type: ipnet
    access: deny
    origin: destination
    address:
      - "172.254.161.0/24"
