# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build Darwin x86
      run: GOOS=darwin GOARCH=amd64 go build -v -o rocket-proxy_darwin_x86 ./../../cmd/*.go
      
    - name: Build Linux x86
      run: GOOS=linux GOARCH=amd64 go build -v -o rocket-proxy_linux_x86 ./../../cmd/*.go

    - name: Test
      run: go test -v ./../../

